# Build script
image: Visual Studio 2017
init:
  - git config --global core.autocrlf true

# Build script
build_script:
  - ps: .\build.ps1 --target="Default"

# Tests
test: off

# Branches to build
branches:
  # Whitelist
  only:
    - master

# Build cache
cache:
- tools -> build.cake
- packages -> build.cake